apiVersion: v1                                       
kind: ConfigMap                                      
metadata:                                            
  name: prometheus-config
  namespace: f5tt
data:                                                
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval: 15s
      scrape_timeout: 8s
    rule_files:
    scrape_configs:
      # Configuration for pull mode
      #- job_name: 'f5tt'
      #  scrape_interval: 10s
      #  scrape_timeout: 8s
      #  static_configs:
      #  - targets:
      #    - f5tt.miller.com

      # Configuration for push mode
      #- job_name: 'pushgateway'
      #  scrape_interval: 120s
      #  scrape_timeout: 120s
      #  static_configs:
      #  - targets:
      #    - pushgateway.f5tt.miller.com

      # Configuration for push and pull mode
      - job_name: 'pushgateway'
        scrape_interval: 120s
        scrape_timeout: 120s
        static_configs:
        - targets:
          - pushgateway.f5tt.miller.com
          - f5tt.miller.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: f5tt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-prometheus
  storageClassName: storage-class-xc-ce
  selector:
    matchLabels: 
      storage-name: pvc-prometheus
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prometheus
  labels:
    kubernetes.io/hostname: cmiller-sno
    storage-name: pvc-prometheus
    storage.openshift.com/local-volume-owner-name: local-volume-xc
    storage.openshift.com/local-volume-owner-namespace: openshift-local-storage
    storage.openshift.com/owner-kind: LocalVolume
    storage.openshift.com/owner-name: local-volume-xc
    storage.openshift.com/owner-namespace: openshift-local-storage
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
    storage.openshift.com/device-name: sdb
spec:
  capacity:
    storage: 10Gi
  local:
    path: /mnt/local-storage/storage-class-xc-ce
    fsType: xfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage-class-xc-ce
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cmiller-sno
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: f5tt
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
        args:
          - "--storage.tsdb.retention.time=730d"
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.enable-admin-api"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: pvc-prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: f5tt
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
  selector:
    app: prometheus
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: f5tt
  annotations:
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
    #nginx.com/health-checks: "true"
  labels:
    app: prometheus
    tier: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.miller.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
